# Model configuration
model:
  model_hub: ../../hub/                        # Path to the model file
  model_class: SimpleChessNet                # Name of the model class

# Dataset configuration
dataset:
  train_path: chessbot/dataset/train  # Path to training PGN dataset
  test_path: chessbot/dataset/test    # Path to test PGN dataset
  samples_train: 500                                                    # Number of training sample files
  samples_test: 20                                                      # Number of test sample files
  num_threads: 20                                                       # Number of threads for dataset loading

# Training configuration
training:
  num_rounds: 50                        # Number of times to sample from datasettraining rounds
  batchsize: 3072                       # Batch size (test/train)
  lr: 0.0005                            # Learning rate
  min_lr: 0.00005                       # Minimum learning rate
  scheduler: cosine                     # Learning rate scheduler
  warmup_lr: 0.00005                    # Initial learning rate during warmup
  warmup_iters: 200                     # Number of warmup iterations
  warmup_strategy: cos                  # Warmup strategy
  scheduler_iters: 100000               # Total scheduler steps
  optimizer: adamw                      # Optimizer
  compile: true                         # Compile the model
  amp: 'no'                             # automatic mixed precision: 'no','fp16','bf16' or 'fp8'
  grad_clip: 1.0                        # Gradient clipping norm value.
  grad_accum: 0                         # Gradient accumulation steps. Greater than 0 to enable
  device: cuda                          # Device to train on
  output_dir: ./                        # Output directory for training artifacts

# Logging configuration
logging:
  log_every: 200                        # Log metrics every N iterations
  validation_every: 20000               # Validate the model every N iterations
  wandb: true                           # Enable logging to Weights & Biases
  wandb_project: chessbot               # W&B project name

