# Model configuration
model:
  model_hub: ../../models/              # Path to the directory containing models
  model_file: null                      # Path to the model file. Will be used instead of the hub 
  name: simple_chessnet                 # Name of the model class

# Dataset configuration
dataset:
  data_path: /dataset                   # Path dataset containing train/ and test/ directories
  size_train: 500                       # Number of files to sample and train on
  size_test: 20                         # Number of files to sample and test on.
  num_threads: 1                        # Number of threads for dataset loading

# Training configuration
train:
  rounds: 1                             # Number of times to sample from dataset
  epochs: 1                             # Number of epochs to train on sampled data
  batch_size: 1024                      # Batch size (test/train)
  validation_every: 20000               # Validate the model every N iterations
  lr: 0.0005                            # Learning rate
  min_lr: 0.00005                       # Minimum learning rate
  scheduler: cosine                     # Learning rate scheduler ('linear' or 'cosine')
  warmup_lr: 0.00005                    # Initial learning rate during warmup
  warmup_iters: 0                       # Number of iterations going from warmup_lr to lr
  warmup_strategy: cos                  # Warmup strategy
  scheduler_iters: 100000               # Total scheduler steps (in iterations)
  optimizer: adamw                      # Optimizer
  compile: false                        # Compile the model
  amp: 'no'                             # automatic mixed precision: 'no','fp16','bf16' or 'fp8'
  grad_clip: 1.0                        # Gradient clipping norm value.
  grad_accum: 0                         # Gradient accumulation steps. Greater than 0 to enable
  device: cuda                          # Device to train on
  output_dir: ./                        # Output directory for training artifacts
  checkpoint_dir: null                  # Checkpoint directory from previous training

# Logging configuration
logging:
  log_every: 200                        # Log metrics every N iterations
  wandb: false                          # Enable logging to Weights & Biases
  wandb_project: chessbot               # W&B project name

