# Model configuration
model:
  model_hub: ../../hub/                    # Path to the directory containing models
  model_file: null                         # Path to the model file. Will be used instead of the hub 
  name: simple_chessnet              # Name of the model class

# Dataset configuration
dataset:
  train_path: /home/kage/chess_workspace/PGN_dataset/Dataset-new/train  # Path to training PGN dataset
  test_path: /home/kage/chess_workspace/PGN_dataset/Dataset-new/test    # Path to test PGN dataset
  size_train: 500                                                    # Number of files to sample and train on
  size_test: 20                                                      # Number of files to sample and test on.
  num_threads: 1                                                     # Number of threads for dataset loading

# Training configuration
train:
  rounds: 50                        # Number of times to sample from dataset
  epochs: 1                             # Number of epochs to train on sampled data
  batch_size: 1024                      # Batch size (test/train)
  lr: 0.0005                            # Learning rate
  min_lr: 0.00005                       # Minimum learning rate
  validation_every: 20000               # Validate the model every N iterations
  scheduler: cosine                     # Learning rate scheduler
  warmup_lr: 0.00005                    # Initial learning rate during warmup
  warmup_iters: 200                     # Number of warmup iterations
  warmup_strategy: cos                  # Warmup strategy
  scheduler_iters: 100000               # Total scheduler steps
  optimizer: adamw                      # Optimizer
  compile: true                         # Compile the model
  amp: 'no'                             # automatic mixed precision: 'no','fp16','bf16' or 'fp8'
  grad_clip: 1.0                        # Gradient clipping norm value.
  grad_accum: 0                         # Gradient accumulation steps. Greater than 0 to enable
  device: cuda                          # Device to train on
  output_dir: ./                        # Output directory for training artifacts

# Logging configuration
logging:
  log_every: 200                        # Log metrics every N iterations
  wandb: false                           # Enable logging to Weights & Biases
  wandb_project: chessbot               # W&B project name

